### PR TITLE
Update process-for-new-or-revised-policies.md

### PR DESCRIPTION
**Pull request by balos1**

### CODE REVIEW

**Comment by ulrikeyang** [comment]
This looks fine, except for we need to fix markdown. Right now the following does not appear:
<what is currently the most appropriate mail list> 
Once this has been fixed I will approve it.

**Comment by ulrikeyang** [comment]
This looks fine, but we need to fix the markdown file.
Right now the following does not appear:
<what is currently the most appropriate mail list> 
<<what is currently the most appropriate mail list>>

**Comment by ulrikeyang** [comment]
This looks fine, but we need to fix the following which right now does not appear in mark down:
what is currently the most appropriate mail list

**Comment by balos1** [comment]
@ulrikeyang I have added the mailing list address now.

**Review by ulrikeyang — APPROVED** [review]

**Pull request merged**
